[project]
name = "PyGB"
version = "2025.06"
readme = "README.md"

requires-python = ">= 3.12"

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
ignore = ["E741"]  # ambiguous-variable-name
